# Generated by Django 4.0.1 on 2022-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0002_mywallet_users_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywallet',
            old_name='amount',
            new_name='admission',
        ),
        migrations.AddField(
            model_name='mywallet',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
    ]
