# Generated by Django 4.0.1 on 2022-01-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_wallet', '0003_rename_amount_mywallet_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mywallet',
            name='users_date',
            field=models.TextField(),
        ),
    ]
