# Generated by Django 4.0.1 on 2022-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0004_alter_mywallet_username_alter_mywallet_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='admission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mywallet',
            name='consumption',
            field=models.IntegerField(),
        ),
    ]
