# Generated by Django 4.0.1 on 2022-01-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0005_alter_mywallet_admission_alter_mywallet_consumption'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mywallet',
            table='my_second_wallet',
        ),
    ]
